name = "chatbot-telegram-game-make100"
main = "cloudflare-worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
GAME_SHORT_NAME = "make100"
GAME_URL = "https://gamemake100.pages.dev"
BOT_USERNAME = "Game_Make100_bot"
# BOT_TOKEN = "..." # Обязательно укажите в дашборде Cloudflare как Secret (Settings -> Variables and Secrets)
